-- Supabase SQL Editor에서 한 번 실행하세요.

create table if not exists public.teacher_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_sessions (
  id uuid primary key,
  student_id text not null,
  user_agent text,
  started_at timestamptz not null default now(),
  submitted_at timestamptz
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.activity_sessions(id) on delete cascade,
  student_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_answers (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.activity_sessions(id) on delete cascade,
  student_id text not null,
  activity_key text not null,
  answer_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.teacher_profiles enable row level security;
alter table public.activity_sessions enable row level security;
alter table public.activity_events enable row level security;
alter table public.activity_answers enable row level security;

-- 학생(로그인하지 않은 익명 브라우저)은 기록 생성만 가능
create policy "anon_insert_sessions" on public.activity_sessions for insert to anon with check (true);
create policy "anon_update_sessions" on public.activity_sessions for update to anon using (true) with check (true);
create policy "anon_insert_events" on public.activity_events for insert to anon with check (true);
create policy "anon_insert_answers" on public.activity_answers for insert to anon with check (true);

-- 교사 여부 확인용 함수
create or replace function public.is_teacher()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.teacher_profiles tp where tp.user_id = auth.uid());
$$;

create policy "teacher_read_own_profile" on public.teacher_profiles for select to authenticated using (user_id=auth.uid());
create policy "teacher_read_sessions" on public.activity_sessions for select to authenticated using (public.is_teacher());
create policy "teacher_read_events" on public.activity_events for select to authenticated using (public.is_teacher());
create policy "teacher_read_answers" on public.activity_answers for select to authenticated using (public.is_teacher());

-- 교사 계정 생성 후 아래 문장을 실제 UUID로 바꿔 한 번 실행:
-- insert into public.teacher_profiles(user_id, display_name)
-- values ('SUPABASE_AUTH_USER_UUID', '교사');
